backend:
  name: git-gateway
  branch: main

media_folder: 'public/uploads'
public_folder: '/uploads'

collections:
  - name: 'blog'
    label: 'Blog Posts'
    folder: 'src/content/blog'
    create: true
    delete: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Publish Date', name: 'pubDate', widget: 'datetime', format: 'YYYY-MM-DDTHH:mm:ss.SSSZ', picker_utc: true, required: true }
      - { label: 'Author', name: 'author', widget: 'string', required: true }
      - { label: 'Featured Image', name: 'image', widget: 'image', required: false }
      - { label: 'Description', name: 'description', widget: 'string', required: true }
      - { label: 'Tags', name: 'tags', widget: 'list', allow_add: true, field: { label: 'Tag', name: 'tag', widget: 'string' }, required: false }
      - { label: 'Body', name: 'body', widget: 'markdown', required: true }
